/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazlab23;

import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author ahmet
 */
public class ilkEkran extends javax.swing.JDialog {
    private ArrayList<musluk> musluklar =new ArrayList<>();
    private DefaultTableModel muslukListeleModel;
    private DefaultTableModel baglantilarModel;
    private int[] muslukSayisi;
    private      JComboBox<Integer> MusluklarcomboBox = new JComboBox<>();
    private TableColumn Musluk1Column,Musluk2Column;
    public ilkEkran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        muslukListeleModel=(DefaultTableModel) musluklarListeleTable.getModel();
        baglantilarModel=(DefaultTableModel) baglantilarTable.getModel();
        MuslukListelejPanel.setVisible(false);
        BaglantilarJpanel.setVisible(false);
        Musluk1Column = baglantilarTable.getColumnModel().getColumn(0);
        Musluk2Column = baglantilarTable.getColumnModel().getColumn(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MuslukSecComboBox = new javax.swing.JComboBox<>();
        MuslukListelejPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        musluklarListeleTable = new javax.swing.JTable();
        BaglantilarJpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        baglantilarTable = new javax.swing.JTable();
        baglantiEkleBtn = new javax.swing.JButton();
        DevamEtBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Musluk Sayısı Seçiniz:");

        MuslukSecComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        MuslukSecComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuslukSecComboBoxActionPerformed(evt);
            }
        });

        musluklarListeleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Musluk ID", "Musluklar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        musluklarListeleTable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(musluklarListeleTable);
        if (musluklarListeleTable.getColumnModel().getColumnCount() > 0) {
            musluklarListeleTable.getColumnModel().getColumn(0).setResizable(false);
            musluklarListeleTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout MuslukListelejPanelLayout = new javax.swing.GroupLayout(MuslukListelejPanel);
        MuslukListelejPanel.setLayout(MuslukListelejPanelLayout);
        MuslukListelejPanelLayout.setHorizontalGroup(
            MuslukListelejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuslukListelejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MuslukListelejPanelLayout.setVerticalGroup(
            MuslukListelejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuslukListelejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        baglantilarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Musluk 1 - ID", "Musluk 2 -ID", "Kapasite"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        baglantilarTable.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                baglantilarTableComponentRemoved(evt);
            }
        });
        jScrollPane2.setViewportView(baglantilarTable);
        if (baglantilarTable.getColumnModel().getColumnCount() > 0) {
            baglantilarTable.getColumnModel().getColumn(0).setResizable(false);
            baglantilarTable.getColumnModel().getColumn(1).setResizable(false);
            baglantilarTable.getColumnModel().getColumn(2).setResizable(false);
        }

        baglantiEkleBtn.setText("Yeni Bağlantı");
        baglantiEkleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baglantiEkleBtnActionPerformed(evt);
            }
        });

        DevamEtBtn.setText("Devam Et");
        DevamEtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevamEtBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BaglantilarJpanelLayout = new javax.swing.GroupLayout(BaglantilarJpanel);
        BaglantilarJpanel.setLayout(BaglantilarJpanelLayout);
        BaglantilarJpanelLayout.setHorizontalGroup(
            BaglantilarJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BaglantilarJpanelLayout.createSequentialGroup()
                .addContainerGap(550, Short.MAX_VALUE)
                .addGroup(BaglantilarJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DevamEtBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(baglantiEkleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(BaglantilarJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BaglantilarJpanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(172, Short.MAX_VALUE)))
        );
        BaglantilarJpanelLayout.setVerticalGroup(
            BaglantilarJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaglantilarJpanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(baglantiEkleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(DevamEtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(BaglantilarJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BaglantilarJpanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MuslukSecComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MuslukListelejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BaglantilarJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MuslukSecComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(MuslukListelejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(BaglantilarJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MuslukSecComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuslukSecComboBoxActionPerformed
       int secilen =MuslukSecComboBox.getSelectedIndex();
       secilen++;
       muslukListeleModel.setRowCount(0);
       muslukSayisi=new int[secilen];
       for(int i=0;i<secilen;i++){
           String muslukAdi=(i+1)+". musluk";
           Object[] x={i+1,muslukAdi};
           muslukListeleModel.addRow(x);
           MusluklarcomboBox.addItem(i+1);
       }
       Musluk1Column.setCellEditor(new DefaultCellEditor(MusluklarcomboBox));
       Musluk2Column.setCellEditor(new DefaultCellEditor(MusluklarcomboBox));
       MuslukListelejPanel.setVisible(true);
       baglantilarModel.setRowCount(0);
       BaglantilarJpanel.setVisible(true);
     
    }//GEN-LAST:event_MuslukSecComboBoxActionPerformed

    private void baglantilarTableComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_baglantilarTableComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_baglantilarTableComponentRemoved

    private void baglantiEkleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baglantiEkleBtnActionPerformed
       int sayi= baglantilarModel.getRowCount();
       sayi++;
      
       baglantilarModel.setRowCount(sayi);
    }//GEN-LAST:event_baglantiEkleBtnActionPerformed

    private void DevamEtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevamEtBtnActionPerformed
        
        for(int i=1;i<=muslukSayisi.length;i++){
            musluklar.add(new musluk(i));
        }
        for(int i=0;i<baglantilarTable.getRowCount();i++){
            int musluk1=(int) baglantilarModel.getValueAt(i,0);
            int musluk2=(int) baglantilarModel.getValueAt(i,1);
            int kapasite=(int) baglantilarModel.getValueAt(i,2);
            baglantiEkle(musluk1, musluk2, kapasite);
            baglantiEkle(musluk2, musluk1, kapasite);
            System.out.println(musluk1+" - "+musluk2 +"= "+ kapasite);
        }
        
        for(musluk i:musluklar){
            System.out.println("Musluk "+i.id);
            for(int j=0;j<i.baglanti.size();j++){
                System.out.println("    "+i.baglanti.get(j).id +"Kapasite:"+i.kapasite.get(j));
            }    
        }
        ekran Ekran=new ekran();
        Ekran.setMusluklar(musluklar);
        Ekran.setVisible(true);
        
    }//GEN-LAST:event_DevamEtBtnActionPerformed
    public void baglantiEkle(int Musluk1ID,int Musluk2ID,int Kapasite){
            musluk Musluk2 = null;
            for(musluk i: musluklar){
                if(i.id==Musluk2ID){
                    Musluk2=i;
                }
            }
            
            for(musluk i: musluklar){
                if(i.id==Musluk1ID){
                    i.baglanti.add(Musluk2);
                    i.kapasite.add(Kapasite);
                }
            }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ilkEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ilkEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ilkEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ilkEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ilkEkran dialog = new ilkEkran(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BaglantilarJpanel;
    private javax.swing.JButton DevamEtBtn;
    private javax.swing.JPanel MuslukListelejPanel;
    private javax.swing.JComboBox<String> MuslukSecComboBox;
    private javax.swing.JButton baglantiEkleBtn;
    private javax.swing.JTable baglantilarTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable musluklarListeleTable;
    // End of variables declaration//GEN-END:variables
}
